### PR TITLE
Using bumpalo now, some region experimentation too

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
I decided to come back to this project after awhile and... holy cow preallocating arenas suck. I just do not want to have to think about them when working on new features, and that factor was blocking me from making any real progress.

**Long story short, I completely deleted `curse_arena` and replaced it with `bumpalo`.**

There's just too many benefits _not_ to switch:
1. Dynamically sized so we don't have to worry about preallocating and visitors (bleh)
2. Can be used for any type, no more `ArenaAllocatable` traits. I thought it would be bad to pack everything into the same buffers because of alignment and padding reasons, but *surprise* pretty much everything has alignment 8 (or occasionally 4). This means there's very very little wasted space.
3. We can still preallocate contiguous slices with `Bump::alloc_slice_fill_iter`, which preallocates with the `size_hint()` of the `ExactSizeIterator` iter and panics if the iter is too long. I had to create a custom `Iter` type for this (see `curse_ast::ast::Iter`) since chaining is no longer `ExactSizeIterator` for [reasons](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html#when-shouldnt-an-adapter-be-exactsizeiterator). Overall though this cleans up a LOT of code so it's definitely worth it.
4. `bumpalo` has some crazy optimizations, such as [bumping downwards](https://fitzgeraldnick.com/2019/11/01/always-bump-downwards.html) and aligning to page boundaries.
5. No more unsafe code written by me (this is the biggest upside)

# Bad news

`cargo +nightly miri test` reports memory leaks. I even added `#![forbid(unsafe_code)]` everywhere, so it's not me! Making this PR a draft until this is resolved or decided that we don't care.

# Regions

There's also some very experimental regions syntax in here, I was toying around.

### CODE REVIEW

**Review by William103 — COMMENTED** [review]
Sounds good to me. I'd just maybe add that it's not the end of the world if we have a memory leak or a slightly suboptimal way of storing everything. No need for premature optimizations. Also the region stuff is looking good! No idea how we'll implement it, but I'm sure we'll figure out something.

**Comment by QnnOkabayashi** [comment]
> No need for premature optimizations.

Agreed, this is my primary motive for switching to bumpalo in the first place. It's just a nice side effect that bumpalo's trade offs are well aligned with our use case :)

**Comment by QnnOkabayashi** [comment]
I figured it out. We're putting AST elements (some of which contain `Vec<T>`) into a bump allocator, which doesn't run destructors, thus leaking them.

Some possible ideas:
1. use `bumpalo::boxed::Box` to store pointers between exprs. This will fix the issue because drop destructors will be run, but requires adding `bumpalo` to `curse_ast` as a dep.
2. Same as above, but use a little bit of `unsafe` and write our own `Box` type that will run the destructor. Less compilation but I have to write unsafe code, which has been a bad idea historically. It would also be frustrating because the constructor would need to take a `&mut T` if we don't want to touch `bumpalo`, and so it would have to be an unsafe function that requires that the referenced value isn't dropped outside of our custom box type.
3. Do the normal `T*/T+` patterns in lalrpop, but then drain them into `bumpalo::collections::vec::Vec` and then call [`.into_bump_slice()`](https://docs.rs/bumpalo/latest/bumpalo/collections/vec/struct.Vec.html#method.into_bump_slice) so we can store everything as a slice.
4. Store sequences as a linked list backed by the bump allocator.

I tried 4, but was getting weird grammar ambiguities. I had this:
```rust
struct Seq<'ast, T> {
    value: T,
    next: Option<&'ast Self>,
}
```
where `Option<&'ast Seq<'ast, T>>` is used as a potentially empty sequence, and `&'ast Seq<'ast, T>` was used as a nonempty sequence.

In `grammar.lalrpop`, it was defined as follows:
```
Seq<T>: &'ast Seq<T> = {
    <value:T> <next:Seq<T>?> => parser.bump.alloc(Seq { value, next }),
};
```

But then I would get ambiguity whenever I did something like this:
```
Seq<(Arm, ",")>? Arm?
```

I wasn't really sure how to fix this, so I tried out 3 and got a combinatorial explosion of ambiguity errors that filled my entire terminal buffer. This was the only difference I did in lalrpop:
```
Slice0<T>: &'ast [T] = {
    T* => bumpalo::collections::vec::Vec::from_iter_in(<>, &parser.bump).into_bump_slice(),
}

Slice1<T>: &'ast [T] = {
    T+ => bumpalo::collections::vec::Vec::from_iter_in(<>, &parser.bump).into_bump_slice(),
}

```
And then replacing instances of `T*` and `T+` with `Slice0<T>` and `Slice1<T>` respectively, as well as changing the definitions in `curse_ast` to use slices instead of vecs. So I guess the `+` and `*` macros in lalrpop are special cased and 1 level of indirection breaks it, which is frustrating but ok because this wasn't my favorite solution anyways.

I'd really like 4 to work because it seems like the "correct" solutions, but I think 1 might be the easiest way forward.

**Comment by QnnOkabayashi** [comment]
Since the problem isn't that bad and potential solutions are known, I'm going to just merge this and open an issue that I'll close once the leaks are fixed.

**Pull request merged**
